### PR TITLE
feat: added ability to handle course errors

### PR DESCRIPTION
**Pull request by omerhabib26**
### Description:

- Integrate and parse CourseEnrollmentDetails API
- Handle CourseAccess Errors on course Dashboard
- Update UI based on CourseAccess Errors.

figma: https://www.figma.com/design/iZ56YMjbRMShCCDxqrqRrR/Open-edX-Mobile-App-All-Screens-v2.2?node-id=10061-77377&t=Gmoit4lBJxrmRE9f-4

| AuditExpiredNotUpgradeable | AuditExpiredUpgradeable | UnknownError | CourseNotYetStarted |
|----------------|----------------------|-------------------------------|---------------------------|
| ||||

### CODE REVIEW

**Review by dixidroid — COMMENTED** [review]
just small UI inaccuracies

missed details:



The button design does not match Figma (text and landscape mode)

**Comment by omerhabib26** [comment]
Hey @dixidroid, Moiz approved these changes as we have to open a Modal for purchase that's why we hide that UI part, and the button design is common for whole app.

**Review by dixidroid — APPROVED** [review]

**Review by farhan-arshad-dev — CHANGES_REQUESTED** [review]
I'm supposed to review the IAP flow and found the following issue.

Data is not getting refreshed after the completion of IAP flow when the user doesn't have the course access.

**Review by farhan-arshad-dev — APPROVED** [review]
The IAP Flow from the course dashboard screen is working fine for me.

**Pull request merged**
