### PR TITLE
fix: crash when internet disconnected right after opening a course

### PR DESCRIPTION
**Pull request by dixidroid**
The crash was fixed + added UI handlers for the Home and Videos tabs to stop infinite loading

### CODE REVIEW

**Review by HamzaIsrar12 — COMMENTED** [review]
Hey @dixidroid, the underline issue is resolved. 👏🏻

I noticed a minor issue: we're loading the Video tab content from the cache, but not the Home tab content.

**Steps to reproduce:**

- Open a course and let it load.
- Return to the Main Dashboard.
- Open the course again and quickly switch to airplane mode.
- You’ll see that the Home Tab shows a "No Content" error, while the Videos Tab loads as expected.


https://github.com/user-attachments/assets/b5244788-03e3-4e20-bd7e-9082625040d9

**Comment by dixidroid** [comment]
@HamzaIsrar12 Hi! 
This happens because for the Home tab we need to send 2 more requests to get the course status and course dates, but for the Video tab we only need to get the course structure which was cached.

**Review by HamzaIsrar12 — APPROVED** [review]
Sounds good! Approving this for now, but let's address it with a proper Cache-First approach in a separate PR. 😄

**Comment by HamzaIsrar12** [comment]
Merging with a single approval since we need to include it in the release.

**Pull request merged**
